namespace CoronaDataHelper.JSON {

	public class JSONCoronaVirusData {
		public JSONCountry ABW { get; set; }
		public JSONCountry AFG { get; set; }
		public JSONCountry AGO { get; set; }
		public JSONCountry AIA { get; set; }
		public JSONCountry ALB { get; set; }
		public JSONCountry AND { get; set; }
		public JSONCountry ARE { get; set; }
		public JSONCountry ARG { get; set; }
		public JSONCountry ARM { get; set; }
		public JSONCountry ATG { get; set; }
		public JSONCountry AUS { get; set; }
		public JSONCountry AUT { get; set; }
		public JSONCountry AZE { get; set; }
		public JSONCountry BDI { get; set; }
		public JSONCountry BEL { get; set; }
		public JSONCountry BEN { get; set; }
		public JSONCountry BES { get; set; }
		public JSONCountry BFA { get; set; }
		public JSONCountry BGD { get; set; }
		public JSONCountry BGR { get; set; }
		public JSONCountry BHR { get; set; }
		public JSONCountry BHS { get; set; }
		public JSONCountry BIH { get; set; }
		public JSONCountry BLR { get; set; }
		public JSONCountry BLZ { get; set; }
		public JSONCountry BMU { get; set; }
		public JSONCountry BOL { get; set; }
		public JSONCountry BRA { get; set; }
		public JSONCountry BRB { get; set; }
		public JSONCountry BRN { get; set; }
		public JSONCountry BTN { get; set; }
		public JSONCountry BWA { get; set; }
		public JSONCountry CAF { get; set; }
		public JSONCountry CAN { get; set; }
		public JSONCountry CHE { get; set; }
		public JSONCountry CHL { get; set; }
		public JSONCountry CHN { get; set; }
		public JSONCountry CIV { get; set; }
		public JSONCountry CMR { get; set; }
		public JSONCountry COD { get; set; }
		public JSONCountry COG { get; set; }
		public JSONCountry COL { get; set; }
		public JSONCountry COM { get; set; }
		public JSONCountry CPV { get; set; }
		public JSONCountry CRI { get; set; }
		public JSONCountry CUB { get; set; }
		public JSONCountry CUW { get; set; }
		public JSONCountry CYM { get; set; }
		public JSONCountry CYP { get; set; }
		public JSONCountry CZE { get; set; }
		public JSONCountry DEU { get; set; }
		public JSONCountry DJI { get; set; }
		public JSONCountry DMA { get; set; }
		public JSONCountry DNK { get; set; }
		public JSONCountry DOM { get; set; }
		public JSONCountry DZA { get; set; }
		public JSONCountry ECU { get; set; }
		public JSONCountry EGY { get; set; }
		public JSONCountry ERI { get; set; }
		public JSONCountry ESH { get; set; }
		public JSONCountry ESP { get; set; }
		public JSONCountry EST { get; set; }
		public JSONCountry ETH { get; set; }
		public JSONCountry FIN { get; set; }
		public JSONCountry FJI { get; set; }
		public JSONCountry FLK { get; set; }
		public JSONCountry FRA { get; set; }
		public JSONCountry FRO { get; set; }
		public JSONCountry GAB { get; set; }
		public JSONCountry GBR { get; set; }
		public JSONCountry GEO { get; set; }
		public JSONCountry GGY { get; set; }
		public JSONCountry GHA { get; set; }
		public JSONCountry GIB { get; set; }
		public JSONCountry GIN { get; set; }
		public JSONCountry GMB { get; set; }
		public JSONCountry GNB { get; set; }
		public JSONCountry GNQ { get; set; }
		public JSONCountry GRC { get; set; }
		public JSONCountry GRD { get; set; }
		public JSONCountry GRL { get; set; }
		public JSONCountry GTM { get; set; }
		public JSONCountry GUM { get; set; }
		public JSONCountry GUY { get; set; }
		public JSONCountry HKG { get; set; }
		public JSONCountry HND { get; set; }
		public JSONCountry HRV { get; set; }
		public JSONCountry HTI { get; set; }
		public JSONCountry HUN { get; set; }
		public JSONCountry IDN { get; set; }
		public JSONCountry IMN { get; set; }
		public JSONCountry IND { get; set; }
		public JSONCountry IRL { get; set; }
		public JSONCountry IRN { get; set; }
		public JSONCountry IRQ { get; set; }
		public JSONCountry ISL { get; set; }
		public JSONCountry ISR { get; set; }
		public JSONCountry ITA { get; set; }
		public JSONCountry JAM { get; set; }
		public JSONCountry JEY { get; set; }
		public JSONCountry JOR { get; set; }
		public JSONCountry JPN { get; set; }
		public JSONCountry KAZ { get; set; }
		public JSONCountry KEN { get; set; }
		public JSONCountry KGZ { get; set; }
		public JSONCountry KHM { get; set; }
		public JSONCountry KNA { get; set; }
		public JSONCountry KOR { get; set; }
		public JSONCountry KWT { get; set; }
		public JSONCountry LAO { get; set; }
		public JSONCountry LBN { get; set; }
		public JSONCountry LBR { get; set; }
		public JSONCountry LBY { get; set; }
		public JSONCountry LCA { get; set; }
		public JSONCountry LIE { get; set; }
		public JSONCountry LKA { get; set; }
		public JSONCountry LSO { get; set; }
		public JSONCountry LTU { get; set; }
		public JSONCountry LUX { get; set; }
		public JSONCountry LVA { get; set; }
		public JSONCountry MAR { get; set; }
		public JSONCountry MCO { get; set; }
		public JSONCountry MDA { get; set; }
		public JSONCountry MDG { get; set; }
		public JSONCountry MDV { get; set; }
		public JSONCountry MEX { get; set; }
		public JSONCountry MKD { get; set; }
		public JSONCountry MLI { get; set; }
		public JSONCountry MLT { get; set; }
		public JSONCountry MMR { get; set; }
		public JSONCountry MNE { get; set; }
		public JSONCountry MNG { get; set; }
		public JSONCountry MNP { get; set; }
		public JSONCountry MOZ { get; set; }
		public JSONCountry MRT { get; set; }
		public JSONCountry MSR { get; set; }
		public JSONCountry MUS { get; set; }
		public JSONCountry MWI { get; set; }
		public JSONCountry MYS { get; set; }
		public JSONCountry NAM { get; set; }
		public JSONCountry NCL { get; set; }
		public JSONCountry NER { get; set; }
		public JSONCountry NGA { get; set; }
		public JSONCountry NIC { get; set; }
		public JSONCountry NLD { get; set; }
		public JSONCountry NOR { get; set; }
		public JSONCountry NPL { get; set; }
		public JSONCountry NZL { get; set; }
		public JSONCountry OMN { get; set; }
		public JSONCountry PAK { get; set; }
		public JSONCountry PAN { get; set; }
		public JSONCountry PER { get; set; }
		public JSONCountry PHL { get; set; }
		public JSONCountry PNG { get; set; }
		public JSONCountry POL { get; set; }
		public JSONCountry PRI { get; set; }
		public JSONCountry PRT { get; set; }
		public JSONCountry PRY { get; set; }
		public JSONCountry PSE { get; set; }
		public JSONCountry PYF { get; set; }
		public JSONCountry QAT { get; set; }
		public JSONCountry ROU { get; set; }
		public JSONCountry RUS { get; set; }
		public JSONCountry RWA { get; set; }
		public JSONCountry SAU { get; set; }
		public JSONCountry SDN { get; set; }
		public JSONCountry SEN { get; set; }
		public JSONCountry SGP { get; set; }
		public JSONCountry SLB { get; set; }
		public JSONCountry SLE { get; set; }
		public JSONCountry SLV { get; set; }
		public JSONCountry SMR { get; set; }
		public JSONCountry SOM { get; set; }
		public JSONCountry SRB { get; set; }
		public JSONCountry SSD { get; set; }
		public JSONCountry STP { get; set; }
		public JSONCountry SUR { get; set; }
		public JSONCountry SVK { get; set; }
		public JSONCountry SVN { get; set; }
		public JSONCountry SWE { get; set; }
		public JSONCountry SWZ { get; set; }
		public JSONCountry SXM { get; set; }
		public JSONCountry SYC { get; set; }
		public JSONCountry SYR { get; set; }
		public JSONCountry TCA { get; set; }
		public JSONCountry TCD { get; set; }
		public JSONCountry TGO { get; set; }
		public JSONCountry THA { get; set; }
		public JSONCountry TJK { get; set; }
		public JSONCountry TLS { get; set; }
		public JSONCountry TTO { get; set; }
		public JSONCountry TUN { get; set; }
		public JSONCountry TUR { get; set; }
		public JSONCountry TWN { get; set; }
		public JSONCountry TZA { get; set; }
		public JSONCountry UGA { get; set; }
		public JSONCountry UKR { get; set; }
		public JSONCountry URY { get; set; }
		public JSONCountry USA { get; set; }
		public JSONCountry UZB { get; set; }
		public JSONCountry VAT { get; set; }
		public JSONCountry VCT { get; set; }
		public JSONCountry VEN { get; set; }
		public JSONCountry VGB { get; set; }
		public JSONCountry VIR { get; set; }
		public JSONCountry VNM { get; set; }
		public JSONCountry WLF { get; set; }
		public JSONCountry OWID_KOS { get; set; }
		public JSONCountry YEM { get; set; }
		public JSONCountry ZAF { get; set; }
		public JSONCountry ZMB { get; set; }
		public JSONCountry ZWE { get; set; }
		public JSONCountry OWID_WRL { get; set; }
	}
}