CoronaDataHelper.exe coronadata-JHUCSSE.xlsx OurWorldInData
CoronaDataHelper.exe coronadata_worldometer.xlsx Worldometer
CoronaDataHelper.exe coronadata_germany.xlsx GermanyJHUCSSEGIT
CoronaDataHelper.exe coronadata_germanyRKI.xlsx GermanyMarlonLueckert
CoronaDataHelper.exe coronadata_germany_multisource.xlsx GermanyOnly



